### ISSUE TITLE
every time you click on "story" tab, it keeps crashing

### ISSUE THREAD

**Issue by xinylin360** [WellnessLab/adc_caregiver#111] opened 2019-03-20 17:00 UTC

**Comment by hermansaksono** [comment] 2019-03-20 21:58
I believe this is caused by to the database changes. Updating to version 1.0.3 should fix this problem.

I'm going to close this, but feel free to reopen this if the issue persists in version 1.0.3.

**Closed by hermansaksono** 2019-03-20 21:58 UTC
