### ISSUE TITLE
App says I’m on day 5 when it’s my 6th day of challenge

### ISSUE THREAD

**Issue by xinylin360** [WellnessLab/adc_caregiver#94] opened 2019-03-11 22:53 UTC

**Comment by xinylin360** [comment] 2019-03-13 20:19
as soon as the day is greater than 4, the nursery page shows the wrong date

**Comment by hermansaksono** [comment] 2019-03-26 18:21
Closed in PR 46. The issue was caused by a rounding error.

**Closed by hermansaksono** 2019-03-26 18:21 UTC
Labels: high
