### ISSUE TITLE
go&grow database need to have phone ID to send notifications. There should be "fmcToken" under userid (6)

### ISSUE THREAD

**Issue by xinylin360** [WellnessLab/adc_caregiver#81] opened 2019-03-05 23:14 UTC

**Comment by hermansaksono** [comment] 2019-03-07 19:50
@xinylin360, can you try to delete the app from your phone, install it again, and log in again to see if you can get the fcMToken? Thanks.

**Comment by xinylin360** [comment] 2019-03-08 01:58
Just downloaded it again, I will need someone to like or reply to my messages first

**Comment by hermansaksono** [comment] 2019-03-14 12:23
The bug is caused by the missing Google Play Services library on the test phone. I will close this issue and started issue #102.

**Closed by hermansaksono** 2019-03-14 12:23 UTC
